### ISSUE TITLE
nan gfa and odf values when mask includes voxels with 0 dwi signal

### ISSUE THREAD

**Issue by Paolopost** [dipy/dipy#1152]
Processing HCP data I faced with the following use case: the tissue segmentation computed from T1 included some voxels where there was no dwi signal. The fit of the shore model (inside peaks_from_model) raises an exception for the 'nan' odf while it doesn't for gfa.
My usecase was fitting the shore model  multishell data using DIPY and the tissue segmentation was with FAST.

**Comment by arokem** [comment]
This issue is pretty old. I think we can close, but please reopen if this is still a relevant issue that needs follow-up.

**Comment by PaulaTBz** [comment]
Hello there! I ran into the same or at least a similar problem (~70% of my nifti data contains zero values) i.e. I struggle to calculate the GFA maps since the gfa() function returns NaNs in this case. Unfortunately, I cannot find the answer to the problem or any other comment with a solution, so I am posting here. Thank you very much in advance! Any help is greatly appreciated :)

**Comment by pjsjongsung** [comment]
Could you elaborate more on how the NaN values are creating a problem? If it is a problem on further processing or visualization not accepting NaN values, you could try `numpy.nan_to_num` to set it to an arbitrary constant instead.
