### ISSUE TITLE
MDF not working properly

### ISSUE THREAD

**Issue by BramshQamar** [dipy/dipy#1363]
Hello,

I tried to run QuickBundles with MDF on simple data.

     data=[[[1,0,1],[1,1,1],[1,2,1],[1,3,1],[1,4,1]], [[2,4,1], [2,3,1],[2,2,1],[2,1,1],[2,0,1]],
          [[0,1,1],[1,1,1],[2,1,1],[3,1,1],[4,1,1]], [[0,2,1],[1,2,1],[2,2,1],[3,2,1],[4,2,1]]] 

     st=Streamlines(data)

This is how initial data looks:
<img width="550" alt="screen shot 2017-10-20 at 12 36 00 pm" src="https://user-images.githubusercontent.com/26060471/31831996-5cddde28-b593-11e7-92bc-964a095fb722.png">

When I try it with `is_order_invariant=True`

```
    class StreamlineFeature(Feature):
  
           def infer_shape(self, streamline):
                  return streamline.shape
        
           def extract(self, streamline):
                 return streamline

    streamlines=set_number_of_points(st, nb_points=5)
    streamline_feature = StreamlineFeature(is_order_invariant=True)
    metric=MinimumAverageDirectFlipMetric(streamline_feature)
    qb = QuickBundles(threshold=2.0, metric=metric) 
    clusters = qb.cluster(streamlines)    
    print("Nb. clusters:", len(clusters)) 
    print("clusters = ",clusters.clusters)
```

The output is:

`Nb. clusters: 1
clusters =  [Cluster([0, 1, 2, 3])]`

<img width="541" alt="screen shot 2017-10-20 at 12 50 48 pm" src="https://user-images.githubusercontent.com/26060471/31832675-e3d0608e-b595-11e7-8887-dcb818540e46.png">

Results are same when using `is_order_invariant=False`

In actual, MDF is supposed to work differently when `is_order_invariant=True`
It should be giving output something like:
<img width="611" alt="screen shot 2017-10-20 at 1 00 06 pm" src="https://user-images.githubusercontent.com/26060471/31832900-a8d7d97a-b596-11e7-865d-a8dc1b267b38.png">

**Comment by BramshQamar** [comment]
@Garyfallidis @MarcCote

**Comment by Garyfallidis** [comment]
@MarcCote did you see this?

**Comment by MarcCote** [comment]
Hi @BramshQamar and @Garyfallidis. The comparison metric to use with QuickBundles is not the MDF per se. Instead, one should use the `AveragePointwiseEuclideanMetric` (i.e. MDF without the Flip comparison).

The reason is that the QuickBundles algorithm relies on the flip to know how to average two streamlines together. So the class `QuickBundles` refers to a clustering algorithm that 1) is centroid-based, 2) does only one pass over the data 3) is flexible enough to use different metrics for comparing streamlines.

I get this might be confusing with respect to the QuickBundles' paper where the term QuickBundles refers to the combination of the MDF distance and the clustering algorithm. @Garyfallidis maybe we should change the name for the clustering algorithm and remove the option of providing a specified metric to `QuickBundles` class. 
 
The `MinimumAverageDirectFlipMetric` should be used when manually comparing streamlines via the `MinimumAverageDirectFlipMetric.dist()` method.

Note that, this is what it is used by default when calling QuickBundles without providing a metric.

**Comment by Garyfallidis** [comment]
@MarcCote I am not sure what you suggest as a solution here. 
The default QB lustering is using the AveragePointwiseEuclideanMetric
https://github.com/nipy/dipy/blob/master/dipy/segment/clustering.py#L482
The paper calls this function MDF. So people will try to use MDF with QB. And they will trash the paper. 

So we can either rename MDF  metric to link directly to APEM (hackish) or with fix the MDF issue (ideal solution).

**Comment by MarcCote** [comment]
I would argue that MDF is the **symmetrized** version of AveragePointwiseEuclideanMetric, no? 

As a distance metric, MDF is fine (i.e. we can use it independently of QB). That said, QuickBundle's algorithm requires an **asymmetric** distance to work properly. This is because in order to compute the centroids, streamlines need to be averaged together and the direction of a streamline matters in that process.

I don't know if this is any clearer? @Garyfallidis @BramshQamar

**Comment by arokem** [comment]
Did that answer the question @BramshQamar ? Can we close this one?

**Comment by BramshQamar** [comment]
Yes, we can close this issue @arokem.
