### ISSUE TITLE
Could we use gifti for streamlines?

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#1785]
As suggested by @StongeEtienne : this format could be the future of geometric brain data.

We need to benchmark this, to see that it can handle large files. 

And make sure that it can handle data-per-streamline and data-per-node, as well as store the needed header information.

**Comment by jchoude** [comment]
I don't know if that would be a good choice. I think it should be supported, but not sure if that should be the default.

A few questions I have (I'm not expert on Gifti):
- I don't see any clear `intent` that we could use in the spec to specify something like streamlines. The closest I see is `VECTOR`, but not sure if that's exactly applicable. Doesn't seem to have something for "sequences of vectors".

- Related to the previous point, we should avoid doing a was done in lots of software with Nifti, i.e. use it "hackishly" to store what we need. If we come to the conclusion this would be a nice addition, we should work with the Gifti people to ensure this works.

**Comment by StongeEtienne** [comment]
@arokem It would be useful, however I would focus at first on the ".trk" support, since it's an already used format, and we need to be able to support it the best as we can.

For Gifti, as mentionned by @jchoude , Gifti currently support a way to save all vertices (ex: surface points) with "NIFTI_INTENT_POINTSET" and save the triangle (mapping to vertices id) in "NIFTI_INTENT_TRIANGLE".
There is multiple way to use a tranformation matrix ("NIFTI_XFORM_*"), it apply it to "NIFTI_INTENT_POINTSET",

**However**, I don't think there is no standard (directly supported) way to save PolyLine / streamlines (a list of starting index, like VTK polyline), There is a "NIFTI_INTENT_NODE_INDEX" that is similar (saving indices) **but** I think it would be better/safer to simply ask/request a _"NIFTI_INTENT_POLYLINE"_, once we discussed and are persuaded.


In the mean time, if you want to test it (speed/compression), you can generate a "fake" Gifti surface, with vertices from a tractogram and create a "fake" Triangle numpy.array = [[1,2,3],[4,5,6], ... [ , , nb_vertices]] ~= _np.arange(nb_vertices).reshape(-1,3)_.

**Comment by arokem** [comment]
I think the question was answered. Closing.
