### ISSUE TITLE
Did we lose our coverage reporting?

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#1872]
For example, I can't see test coverage reported here, though I would expect it: https://travis-ci.org/nipy/dipy/jobs/548102372

**Comment by jhlegarreta** [comment]
Looks like `codecov` is still reporting the coverage impact for successful PRs. Coverage was also configured for the `Azure CI` `Linux Python37-64bit + OPTIONAL_DEPS + COVERAGE` job but the generated HTML reports seem not be uploaded anywhere.

The `travis CI` service was commented a few days ago so the resource pointed by the link in the issue cannot be retrieved.

Not sure whether `codecov` can be given the `Azure CI`-generated HTML's so that the coverage impact graphs can be displayed again.
