### ISSUE TITLE
Reference for `load_trk` in recobundles example

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#2007]
Reported by Giulia Berto on the [mailing list](https://mail.python.org/archives/list/dipy@python.org/message/6A2DNEGJBMWETNUWIZYE5NGQQJ36F4GK/): 

"Does then the example "Automatic Fiber Bundle Extraction with RecoBundles" here https://dipy.org/documentation/1.0.0./examples_built/bundle_extraction/ need to be updated? I guess that sft_atlas = load_trk(atlas_file, "same", bbox_valid_check=False) needs a reference rather that "same"."

**Comment by giulia-berto** [comment]
Yes, the reference needed should be the one of the MNI space ICBM 2009a template.

Also, the example source code bundle_extraction.py related to the tutorial is not updated, and gives the following error:  TypeError: load_trk() missing 1 required positional argument: 'reference'.

**Comment by jhlegarreta** [comment]
@giulia-berto the reported error seems not to be present in DIPY `master`: I've tried running the example and it runs without issues.

Can you tell which DIPY version you are using? Can you try the example in DIPY `master`?

A number of examples had not been updated for the 1.0.0 release but were fixed in PR #1925 for the 1.1.0 release.

Using the `same` value for the `reference` argument is an accepted/documented practice for TRK files (see https://github.com/dipy/dipy/blob/master/dipy/io/streamline.py#L95).

Now, @arokem may be all examples (there are a few `load_trk` calls still present) should use the 
`load_tractogram` interface so as to avoid confusion/increase consistency?

**Comment by jhlegarreta** [comment]
@arokem can you please have a look at the comment above to eventually close this issue?

Also, if you think all examples should be using `load_tractogram` instead of other APIs to load tractograms, let me know and I'll propose a PR.

**Comment by skoudoro** [comment]
Hi @jhlegarreta,

We can not close this issue because we have to update the atlas which has been saved with the wrong affine. So we have to save them with into the mni space and upload them to figshare

However, you are right concerning the second issue. It is done on master.

I do not think that all examples should use `load_tractogram`, `load_trk` is ok

**Comment by jhlegarreta** [comment]
@skoudoro OK, sounds fair.

**Comment by arokem** [comment]
@skoudoro : Is it the MNI template that has the wrong affine? The one you get when you run dipy.data.get_mni_template? I've also recently run into some issues with it, but I think that the affine corrects for the shape, so that it sits in the same place as othe versions of this template that I have examined. At least that's my impression.

**Comment by giulia-berto** [comment]
@jhlegarreta correct, the source code bundle_extraction.py currently runs without errors since it was updated as soon as this issue was opened. 

@arokem @jhlegarreta using `same` as the reference is fine as long as the affine is stored properly in the header. The bundle atlases in figshare that can be retrieved with 'get_bundle_atlas_hcp842()' have been saved with the wrong affine, as @skoudoro said.

**Comment by arokem** [comment]
> The bundle atlases in figshare that can be retrieved with 'get_bundle_atlas_hcp842()' have been saved with the wrong affine

Gocha! I was reading too much into this :-)

**Comment by jhlegarreta** [comment]
@giulia-berto thanks for clarifying this.

**Comment by frheault** [comment]
I would strongly advise using this corrected version of Yeh.
All TRK have the correct affine and are register to a MNI template that is provided.
This would prevent created TRK with wrong header in the future and simplify debugging for a lot of people.

https://drive.google.com/open?id=1pObyKLGJNPFZhMIncYuLn9utJDKb-Uq9

**Comment by giulia-berto** [comment]
Hi @frheault, thank you for providing the corrected version of the atlas. I however found two inconsistencies:
1. The file fused_tractogram.trk has some spurious streamlines that appear as straight lines.
2. The file density_map.nii.gz is not aligned with the other images and trk files (it has a different affine).

**Comment by skoudoro** [comment]
I am closing this issue in favor of #2166. 

@giulia-berto, Can you look at the discussion in #2166 and check if you find the same inconsistencies? 

thank you
