### ISSUE TITLE
DIPY open group meetings, Fall 2020

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#2229]
Hello everyone! 

In Fall 2020, we will have the following meetings: 

- October 21st, noon EST / 6pm CET:  @skoudoro talks about the upcoming DIPY release (issue overview, help on PR, etc...)
- November 4th, noon EST / 6pm CET: @36000 presents [pyAFQ](http://yeatmanlab.github.io/pyAFQ/)
- November 18th, noon EST / 6pm CET: @BramshQamar  presents and runs a demo of BUAN framework. Recently published [here](https://www.nature.com/articles/s41598-020-74054-4). A recording of the talk is now available [here](https://youtu.be/9Ay1rhRTaKU).
- December 2nd, noon EST / 6pm CET: TRX, a community file format: Where do you come from and where do you go? @frheault 

The zoom link for the call is going to be: https://washington.zoom.us/j/95978299081

**Comment by arokem** [comment]
We already have a speaker and topic for our first meeting. If you are interested in a particular topic of discussion, please let us know here.

**Comment by skoudoro** [comment]
Calendar updated, there is a topic for all meeting!

**Comment by skoudoro** [comment]
Hi @dipy/dipy-community,

The meeting on Wednesday (October 21st, noon EST / 6pm CET) will be dedicated to the future Release help, request, advise...
we would really appreciate the presence of:

- @CHrlS98 to talk about spherical harmonics in its PR #2206
- @gabknight to give us feedback about tractography in its PR #2036
- @StongeEtienne to provide us the status of mesh surface and its PR #1648
- @mvgolub or @RafaelNH to provide us the status and plan for the FreeWater DTI (#2132)

Please, feel free to stop by 10-15min in this meeting to give us an update.

As usual, everyone is welcomed if you have any suggestion at the following link: https://washington.zoom.us/j/95978299081

See you all on Wednesday!

**Comment by skoudoro** [comment]
Thank you all for your presence! 

Quick summary:
----------------
#2206 -> spherical harmonics:  we keep the SH legacy, the PR should be done for release 1.3.  The default SH definition might change in DIPY 2.0. We should start slowly the transition and plan a new meeting on January/February

#2036 -> Tractography:  Axtract framework is promising but needs still some works. ETA: March and release 1.5

#1648 -> Mesh / surface: the PR is expected to be done for December and release 1.4. New meeting Needed about mesh module management/design and connection with FURY

#2087 -> FreeWater.  PR will be reshaped (initializer) for the release 1.4 in December. Needs tutorial to explain the advantages and drawbacks

Feel free to edit this comment if it missed informations.

**Comment by gabknight** [comment]
If you want to add the meetings to your google calendar: https://calendar.google.com/calendar/embed?src=1k5r4joom8h1h13c2akm39f6fs%40group.calendar.google.com&ctz=Europe%2FAmsterdam

**Comment by skoudoro** [comment]
Thank you @gabknight.

As a reminder, tomorrow meeting/talk is about [pyAFQ](http://yeatmanlab.github.io/pyAFQ/) by @36000  (November 4th, noon EST / 6pm CET)

See you tomorrow @dipy/dipy-community!

**Comment by 36000** [comment]
Sorry I was late today. Here are the introduction slides I used:
https://docs.google.com/presentation/d/19MiWNjawJNLYq6hA-XEV0X7G1OHpKTJdnYHg3OVFiRk/edit?usp=sharing

Here is an example of how to use the pyAFQ CLI:
https://yeatmanlab.github.io/pyAFQ/usage/index.html
An example config file is attached: [test.toml.zip](https://github.com/dipy/dipy/files/5489800/test.toml.zip)

Here is an example of how to use the pyAFQ API:
https://yeatmanlab.github.io/pyAFQ/auto_examples/plot_afq_api.html#sphx-glr-auto-examples-plot-afq-api-py

Here is a visualization of AFQ results using plotly: https://tinyurl.com/y4wssmk2
Here is a visualization of Reco80 results, which I did not show during the meeting: 
https://gist.githack.com/36000/9a4683a3fe90be14abaccf3d35077e4a/raw/be733dc73aa9a915b655c6fe9b349cebda56be67/sub-103818_dwi_space-RASMM_model-DKI_desc-det-reco80_viz.html

And here are some slides on reliability results that I referenced near the end:
https://docs.google.com/presentation/d/1z_3vWngWiQ4u9LL4TWc-3nu8dzRPZG7r1V-VxGCguuk/edit?usp=sharing

Thank you all for listening! Many great questions / feedback.

**Comment by skoudoro** [comment]
Hi @dipy/dipy-community 

Tomorrow, the talk is about Bundle Analytics (BUAN) by @BramshQamar  (November 18th, noon EST / 6pm CET).

She will introduce her new paper and its integration in DIPY.

See you all tomorrow!

**Comment by skoudoro** [comment]
Hi @dipy/dipy-community,

Next week, We will have a discussion about tractography file format. @frheault will lead the discussion.  This is a follow-up of the thread started by @francopestilli on [a Nibabel issue here](https://github.com/nipy/nibabel/issues/942)

Title: **TRX, a community file format: Where do you come from and where do you go?**
When?  **December 2nd, noon EST / 6pm CET**

@frankyeh, @MarcCote, @bjeurissen @jdtournier @neurolabusc, @mrneont, @jdtournier, @Lestropie, @MichielCottaar, @bjeurissen, @dPys @soichi, you might be interested 😄. Feel free to spread the word

**Comment by francopestilli** [comment]
@skoudoro @arokem @frheault please look at the document the community had built around the initial discussion on the nibabel page https://docs.google.com/document/d/1GOOlG42rB7dlJizu2RfaF5XNj_pIaVl_6rtBSUhsgbE/edit

**Comment by frankyeh** [comment]
Hi All,

    I also help with adding my comments.

    One thing I notice from @frheault <https://github.com/frheault>'s
input is that we seem to have a very different focus on the features. I am
looking for high efficiency in IO and disk space because I am dealing with
a large number of subjects and tracks, whereas he and others may be more
interested in flexibility and extensibility.

    Since a lot of features are antagonistic to each other, which features
should we focus on?

Best,
Frank

**Comment by frheault** [comment]
@frankyeh I think that a C++ implementation of the TRX would provide an interesting speed up for some basic I/O operation. I'm not sure speed is necessarily antagonistic to flexibility and extensibility.

To some extent, a lot of us work with BigData and for a long time TCK and TRK were good enough. So I believe that a 5-10x speed up and reduction of Disk space by a factor 2-3 is a good start.

Out of curiosity, do you compress the streamlines (lossy) using an approach such as: https://www.frontiersin.org/articles/10.3389/fninf.2017.00042/full
It is compatible with TCK/TRK specification, so that's nice.

If you don't like lossy compression, I think loading a big array cannot get much faster than what TRX is, there isn't much way around it.

**Comment by frankyeh** [comment]
>
> @frankyeh <https://github.com/frankyeh> I think that a C++ implementation
> of the TRX would provide an interesting speed up for some basic I/O
> operation. I'm not sure speed is necessarily antagonistic to flexibility
> and extensibility.
>
Sounds encouraging. Once there is a C++ code for TRX, I will surely test it
out.

> Out of curiosity, do you compress the streamlines (lossy) using an
> approach such as:
> https://www.frontiersin.org/articles/10.3389/fninf.2017.00042/full
>
It looks interesting. I will check it out in detail.
Thanks,
Frank

**Comment by neurolabusc** [comment]
@frheault The speedups you are describing may be a straw man. People have proposed [x46 acceleration for TCK](https://github.com/rordenlab/TractographyFormat) files, as well as [x15 accelerations of TRK](https://github.com/nipy/nibabel/issues/943) files. But these suggestions have not been evaluated or adopted by the DiPy/nibabel team. It seems like developers would rather create something new, rather than optimize support for formats that are widespread. 

From first principles, I suspect uncompressed TRX may be a little faster than TCK and considerably faster than TRK. I do think the niche here is to have many of the features we like about TRK with the performance of TCK. Like Frank, I would have preferred a simpler format (indeed, I suggested one). However, I do think the work you have done with TRX has created a format that is simple enough, extensible and does fulfill a lot of the design criteria. I do think you deserve a lot of credit for working on this.

**Comment by Lestropie** [comment]
Given this thread is intended for scheduled DIPY meetings, comments specific to TRX might be better moved to frheault/tractography_file_format#1.

**Comment by skoudoro** [comment]
New schedule for spring 2021 [here](https://github.com/dipy/dipy/issues/2312)

I'm closing this, but this thread should be converted to a [github discussion thread](https://github.com/dipy/dipy/discussions/categories/dipy-online-meeting)
