### ISSUE TITLE
NF: Add "None" options in the CLIs

### ISSUE THREAD

**Issue by areeshatariq** [dipy/dipy#2300]
## Description
The ``None`` value does not work in the CLIs as the value of attributes. 
For example: Adding ``num_threads`` attribute with value ``None`` using ``dipy_gibbs_ringing`` command should be appropriately processed to use all the available threads but currently only positive integers can be passed to the ``num_threads`` attribute.

**Comment by drombas** [comment]
Hi! Following advise from @skoudoro in #2314 I am having a look at issues that might help me prepare for the GSoC.

Regarding this issue I saw the following in `dipy.workflows.flow_runner.run_flow()`:
- when calling `parser.add_workflow(flow)` the specific arguments of the workflow are added  to the parser by inspecting the docstrings of the `run()` method of the workflow. The type of `num_threads` parameter is set to `int`.
- when parsing arguments (`parser.get_flow_args()`) the parser checks that the value supplied for `num_threads` is of the type defined before (`int`) and therefore when it is `None` an error is raised.

The first idea that comes to my mind is to use `0` instead of `None` as  the `num_threads` option to use all available threads but I might be missing something. Does it sound reasonable?

**Comment by skoudoro** [comment]
Hi @drombas,

To answer your question, you should look at the function called by the command line`dipy_gibbs_ringing`.

I let you [look at it here](https://github.com/dipy/dipy/blob/master/dipy/denoise/gibbs.py#L240), but it seems if you use `0`, it will raise an error.

you might have to modify the behavior of this function first. Also, you might look at the codebase to find the use of all the `num_thread` checks if there is a common behavior /rules that we can apply to all of them and avoid this problem again.

I hope it helps!

**Comment by drombas** [comment]
Thanks for the comments! After checking that I think that moving from `None` to `0` as the `num_threads` value for all cores would imply modifying:
- **gibbs.py gibbs_removal()**: modify check `<=0` → `<0,` choose all cores when `num_threads==0` and update docstrings
 - **denoise.py GibbsRingingFlow()**: update docstrings
 - **denoise_gibbs.py**: update example
 - **gibbs_unringing_flow.rst**: update docs
 - **test_gibbs.py**: update tests

It it sounds ok I can make these changes and open a PR.

On another side, I have noticed that `0` is already used instead of `None` to select all threads in [reslice.py](https://github.com/dipy/dipy/blob/7eca4013bd3a407df2fac533ba6cec3b310eb90f/dipy/align/reslice.py) (the variable is named `num_processes`). However, some other functions use `None` ([nlmeans.py](https://github.com/dipy/dipy/blob/7eca4013bd3a407df2fac533ba6cec3b310eb90f/dipy/denoise/nlmeans.py), [bundlemin.pyx](https://github.com/dipy/dipy/blob/7eca4013bd3a407df2fac533ba6cec3b310eb90f/dipy/align/bundlemin.pyx),...). For consistency, it might be interesting to modify also those files to use `0` (maybe on a separated issue/PR?).

**Comment by skoudoro** [comment]
Sounds like a plan! I agree with all the points. Let's avoid using `None` and use `0` or `-1` everywhere for using all the core.

I am fine if you do it all in 1 PR since it is related. Feel free if you want to split it into multiples PR.

Thank you for looking into this @drombas!

**Comment by jhlegarreta** [comment]
Thanks for having a look at this @drombas. A few notes on this:
- Are there any other CLI-related cases where `None` is used by the underlying Python method as a default value for a given argument? It might be worthwhile looking at them before making a decision so that the solution can be consistent across all cases, and be adopted at once for all of them.
- IMHO, keeping `None` would be consistent with what is common in Python, which I'd say is in reality our starting point. When the issue was raised I was more inclined for a solution that dealt with the `None` cases through a dedicated method. Having said that, I have not looked at how feasible that would be.

**Comment by skoudoro** [comment]
Overall, I agree with @jhlegarreta. That's a good point. 

For the general purpose, we need to use something like [here](https://stackoverflow.com/a/48295546) in our [`select_dtype`](https://github.com/dipy/dipy/blob/c846bf5a23b7e95343a9cf231df2653473602456/dipy/workflows/base.py#L260) function.

Concerning the specific case of `num_thread`, this is already not consistent across the codebase. Sometimes it is `0`, other times it is `None`. To me, it makes more sense to have `0` or `-1` which is more common to many libraries and many languages than `None`. Again, this is a specific case here, I would not say the same for another kind of variable.

In the end, this issue raises 2 problems.

**Comment by drombas** [comment]
Thanks @jhlegarreta for sharing your ideas! Also @skoudoro for commenting.
      
It is true that `None` is used as the default for some arguments related with the CLI. However, (please correct me if I am wrong) I think those cases work well when that argument is not entered by the user. 

The problem I noticed with this workflow and `num_threads` is that the default value is `1` and `None` is used to specify a different option (using all threads). This forces the user to explicitly enter `None` resulting on an error when the parser checks that the value is not `int`.

More in general, what you mentioned made me wonder if there might be other arguments with `None` as a non-default option that might be problematic in a CLI context. I imagine we could:
1. Modify the parsing process to handle the case when `None` is entered (not sure how difficult it could be).
2. Check which arguments use `None` as a non-default option and modify them to use other value (as with `num_threads`). I don’t know which impact it could have on code that depends on DIPY.

Which approach do you think is preferable?

**Comment by jhlegarreta** [comment]
> However, (please correct me if I am wrong) I think those cases work well when that argument is not entered by the user.

Have not checked but might be accurate.

> The problem I noticed with this workflow and num_threads is that the default value is 1 and None is used to specify a different option (using all threads). This forces the user to explicitly enter None resulting on an error when the parser checks that the value is not int.

OK, so that added to the above looks like an inconsistent behavior/meaning/use of the `None` parameter. I think that we should stick to the convention of `None` as meaning "no argument provided" (and setting the relevant variable to the appropriate value within the body of the method if necessary; i.e. a mutable default argument), which is what we would expect in Python.

> More in general, what you mentioned made me wonder if there might be other arguments with None as a non-default option that might be problematic in a CLI context. I imagine we could:

Using `None` as a non-default option is counter-intuitive. For a variable like `num_threads` both `0` and `None` seem to require the same explanation, so no difference besides maybe a subjective preference. So IMHO that principles discards the 2 possibilities elaborated.

So for the relevant workflow here, I'd say that we're left with these two options:
- As proposed in #2341, use `0` to mean all threads, keep `1` as the default value, and do not use `None` at all. I guess using all threads is not usually desired to avoid side-effects on other process. This would mean that the default value would remain unchanged, which is good. Also, not specifying the value at all would work regardless of whether the method is called from a Python method or from a CLI.
- Use `None` as a default value to mean all threads (i.e. a mutable default argument), and change all calls (except the test case) to explicitly use `1` to avoid affecting other processes. This has the undesired effect of affecting other software depending on DIPY, needing to discard the `0` value if that is entered. Also, default values are often set as sensible values, and that would not be the case for `None` here.

So considering all that has been said, for the general case of the code base, if we have cases of variables where the default is some (possibly) integer value, and `None` is used as a non-default value within the Python body to set the variable to a meaningful value, I think these should be treated with the solution proposed in #2341. Developers might need to be warned about this (e.g. in our coding style), and be told to use e.g. `0` for such cases.
