### ISSUE TITLE
deform_streamlines for wholebrain tractogram doesn't function properly

### ISSUE THREAD

**Issue by wjy73** [dipy/dipy#2313]
## Description
I'm using deform_streamlines to deform the whole brain tractograms with the warpfields generated by SymmetricDiffeomorphicRegistration. Some of the streamlines extend beyond the skull. It looks like the warping algorithm needs more work. I'm basically using the tutorial example.

**Comment by dPys** [comment]
@wjy73 -- would you be able to provide a screenshot and/or a bit more information about the steps that you are using?

deform_streamlines and transform_streamlines are very sensitive to the voxel grids of the images that you used to learn the diffeomorphic and/or linear mappings. What happens when you first resample your moving and static images to the same voxel grid?

What's really needed that I think would help solve a lot of issues with streamline registration is a streamline resampling function much like nilearn's `resample_to_img` function. @arokem -- what are your thoughts on this?

**Comment by wjy73** [comment]
> @wjy73 -- would you be able to provide a screenshot and/or a bit more information about the steps that you are using?
> 
> deform_streamlines and transform_streamlines are very sensitive to the voxel grids of the images that you used to learn the diffeomorphic and/or linear mappings. What happens when you first resample your moving and static images to the same voxel grid?
> 

Sorry for the late response.
I'm using the HCP dataset, and I used the TDI images generated by mrtrix as the static and moving images for volumetric registration. Here is an example.

![spurioustracts_by_warping](https://user-images.githubusercontent.com/75346773/107013459-52d02600-67d5-11eb-85bc-df0da7821912.png)
After randomly checking the outputs, I find the problem is mostly minor in appearance and the spurious tracts can be removed using a brain mask. 

> What's really needed that I think would help solve a lot of issues with streamline registration is a streamline resampling function much like nilearn's `resample_to_img`. @arokem -- what are your thoughts on this?

Yup, I agree.

**Comment by dPys** [comment]
So other than the spurious tracts outside of the brain (is the tractography actually valid here?), this registration looks correct indeed.

If you are tracking with dipy, selecting only those tracks inside the brain post-hoc is easy:
```
streamlines_in_brain = utils.target(
    streamline_generator, np.eye(4),
    B0_mask_data.astype('bool'), include=True
)
```

But the better way is to actually include the brain mask as a part of your stopping-mask/tissue classifier during the tracking itself so that samples don't get wasted.

@dPys
