### ISSUE TITLE
Transforming individual points with SDR

### ISSUE THREAD

**Issue by alexrockhill** [dipy/dipy#2424]
Is it possible to warp a point in volumetric image space with the SDR mapping?

The "Warping to a Common Atlas" section here https://mne.tools/dev/auto_tutorials/clinical/10_ieeg_localize.html is the goal. The problem is if you can apply the SDR morph with to a point in voxel space using the `sdr.forward` field for instance. My impression is that you would have to round to the nearest voxel to apply the vector field but perhaps there is a way to apply it to an arbitrary point. This would be analogous to the dot product of the affine mapping into real-world space.

cc @larsoner

**Comment by larsoner** [comment]
In other words, we want to take an X/Y/Z point in the "moving" space and gets its corresponding location in the "static" space. For affines this is just `np.dot(affine, (x, y, z, 1))[:3]` but for SDR so far we've resorted to something like 1) creating a volume, 2) putting that point in volumetric space (e.g., via linear interpolation or something), 3) applying the SDR morph, 4) getting the max resulting intensity voxel, and 5) applying the vox2ras to get static image real-world coordinates. Steps 2 and 4 are ugly because they involve rounding/interpolation to/from the volumetric grid. But if the SDR is a deformation of the 3D field (not sure if this is the right term?) it seems like it should in principle steps 1-4 at least should be skippable and any arbitrary continuous/fractional "voxel" (or real-world) location in the moving space should be mappable directly to continuous/fractional static space.

**Comment by alexrockhill** [comment]
So I think you could apply a cubic interpolation to the forward field to get a continuous representation of the field but here is where I got stuck/gave up https://github.com/dipy/dipy/blob/master/dipy/align/imwarp.py#L383:L386 because the warping function needs the affines so you'd have to reimplement it ASAIK.

**Comment by arokem** [comment]
Yes: I believe that you can interpolate into the vector field represented
in the SDR. For example, with streamlines we do something like:

```
import dipy.tracking.streamlines
delta = dts.values_from_volume(dm.backward, streamline, affine)
```

Where `dm` is a `DiffeomorphicMap` object, to get a warp value (`delta`) at
each point along the streamline.

**Comment by skoudoro** [comment]
Hi @alexrockhill, Hi @larsoner,

You can look at this PR https://github.com/dipy/dipy/pull/2369 to fix your problem.

We are adding a function named `transform_points` and `transform_points_inverse` in the SDR function. 

I need to find time to create a tutorial and more tests and it will be ready to be merged. Feel free to test it.
