### ISSUE TITLE
Any chance of arm64 wheels for Mac / Python 3.10?

### ISSUE THREAD

**Issue by matthew-brett** [dipy/dipy#2658]
I see y'all don't yet have Mac `arm64` wheels for Python 3.10.   Would you consider providing them?  Is there anything I can do to help?

**Comment by skoudoro** [comment]
Last time we checked (1-2months), some dependencies did not have wheels for arm64 and python 3.10. 

that's why we could not create it. Let's check it again this week. We just need to add a new CI on https://github.com/MacPython/dipy-wheels. It will also be great if you could add it.

Thank you for pinging us!

**Comment by skoudoro** [comment]
to keep track of it:  https://github.com/MacPython/dipy-wheels/pull/10

**Comment by skoudoro** [comment]
it should be good now (see [here](https://pypi.org/project/dipy/#files)). 

Feel free to reopen the issue if there is still a problem.

closing
