### ISSUE TITLE
Setting `Legacy=True` SH basis is not possible for SH models

### ISSUE THREAD

**Issue by gabknight** [dipy/dipy#3187]
## Description
Currently, the SH-based local model use the `Legacy=True` spherical harmonics basis. `Legacy=True` is currently deprecated. An option should be added to all SH models to support `Legacy=False` basis. It should be set to `True` by default. In future version, legacy should be set to `False` by default.

**Comment by skoudoro** [comment]
Hi @gabknight,

`Legacy=True` is normal and it will switch to `False` in DIPY 2.0

in DIPY 1.x, we do not want to break old code because of the change of spherical harmonics definition. it needs to be voluntary. the deprecation warning is help user to realize this point. 

The important point here is to decide a timeline and a release roadmap/Date for DIPY 2.0

**Comment by skoudoro** [comment]
To be clear, DIPY 2.0 will completely remove legacy option and `legacy=True`.

**Comment by gabknight** [comment]
ok, sounds good, thanks.
