### ISSUE TITLE
Should we enforce float32 in tractography results?

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#837]
See #811

**Comment by samuelstjean** [comment]
Some point also to add  : 

+ Voxel size is in mm
+ stepsize is in 1e-1 mm
+ axon size is what, 1e-6 mm?
+ Saving resulting streamline (but keeping intermediate calculation as float64 if needed, probably not)
as float32 will be precise up to 1e-8, so no loss of precision given the above hypothesis are true.

**Comment by jchoude** [comment]
From experience, I think float32 is enough for tractography results. With regards to questions about selecting from an anatomical dataset, the difference in precision between float32 and float64 will almost never create any problem, since we are mostly comparing to discrete voxel boundaries.

As for intersection with a "mathematical object" (say, a sphere defined with center and radius), you have to be quite lucky to get a case where the result of this on a float32 streamline vs a float64 streamline is not the same.

**Comment by omarocegueda** [comment]
Ok! it's great to know that using float32 is accurate enough for practical purposes in tractography!, that should save a lot of memory.

**Comment by samuelstjean** [comment]
Basically our scripts save everything as float32 (so odf, tracking,
metrics, etc.) since forever without any apparent issue. Except I can't
feed them back to the tracking api, but I'm fixing that, and it's a
different issue. But for numerical stability, it does the job.

2016-01-18 17:21 GMT+01:00 Omar Ocegueda <notifications@github.com>:

**Comment by arokem** [comment]
It does seem like a good idea to me too. Do I understand correctly that
this would require changes in many places in the code-base?

@samuelstjean - since you proposed this : would you mind outlining
where/how this change would need to be implemented?

**Comment by samuelstjean** [comment]
Well, I recon that since many function are used elsewhere (like the registration module for interpolation), just changing the last return of a wholly computed streamline as float 32 should do it. That way, all computation still retain precision, won't break other stuff, and the last step is the conversion. If the tracking work streamline by streamline, that would save 1/2 of the ram for free.

**Comment by MrBago** [comment]
What does enforce mean? Does it mean that we don't attempt to support float64 streamline arrays in some (or all?) functions which take streamlines as arguments?

**Comment by samuelstjean** [comment]
I was more thinking about always returning float32 streamlines from
tracking itself, not touching anything else to not break function, like
interpolation, but recasting inside those function everything.
Currently you cannot use float32 streamlines in most function since they
are hardcoded in cython, but casting them yourself to float64 does not lead
to any precision loss by experience.
So hence returning always float32 streamlines for memory, and upcasting
everything in other functions.

2016-01-26 17:16 GMT+01:00 Bago Amirbekian <notifications@github.com>:

**Comment by samuelstjean** [comment]
Actually the trk file format only works on float32 http://www.trackvis.org/docs/?subsect=fileformat
So the saving/loading stuff is already affected by that regardless, see https://github.com/nipy/nibabel/blob/master/nibabel/trackvis.py#L412

So all in all, it's already happening anyway the instant you save file and load them back up, it's just weird nobody reported the functions not working on float32 then.

**Comment by skoudoro** [comment]
Is it still a relevant discussion after all this time?

Can we close this issue? @jchoude @arokem?

**Comment by arokem** [comment]
I believe so. We can reopen if anyone wants to keep going.
